# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

os:
  - linux
  - osx
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - pip install --user cpp-coveralls
  - wget http://bitbucket.org/eigen/eigen/get/3.3.5.tar.gz -O /tmp/eigen.tar.gz
  - mkdir eigen3 
  - tar -xvzf /tmp/eigen.tar.gz -C eigen3 --strip-components 1
  - cd eigen3 
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install
  - cd .. && cd ..
install:
- cd ${TRAVIS_BUILD_DIR}
# install latest LCOV (1.9 was failing for me) [1]
- wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz
- tar xf lcov_1.11.orig.tar.gz
- sudo make -C lcov-1.11/ install
# install lcov to coveralls conversion + upload tool
- gem install coveralls-lcov
script: 
  - cd ${TRAVIS_BUILD_DIR}
  - ./travis.sh
env:
  
  matrix:
    - BUILD_TYPE=Debug VERBOSE=1
    - BUILD_TYPE=Release VERBOSE=1 CXX_FLAGS=-std=c++11
notifications:
  email: false
sudo: required
after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"