# Build matrix / environment variable are explained on:
# http://about.travis-ci.org/docs/user/build-configuration/
# This file can be validated on:
# http://lint.travis-ci.org/

os:
  - linux
  - osx
language: cpp
compiler:
  - gcc
  - clang
before_install:
  - pip install --user cpp-coveralls
  - wget http://bitbucket.org/eigen/eigen/get/3.3.5.tar.gz -O eigen.tar.gz
  - mkdir eigen3 
  - tar -xvjf eigen.tar.gz -C eigen3 --strip-components 1
  - cd eigen3 
  - mkdir build
  - cd build
  - cmake ..
  - make install
script: ./travis.sh
env:
  matrix:
    - BUILD_TYPE=Debug VERBOSE=1
    - BUILD_TYPE=Release VERBOSE=1 CXX_FLAGS=-std=c++11
notifications:
  email: false
sudo: false
after_success:
  - coveralls --root . -E ".*gtest.*" -E ".*CMakeFiles.*"