version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x64

environment:
  EIGEN3_ROOT:  C:\projects\eigen-eigen-b3f3d4950030\
  Eigen3_DIR: C:\projects\eigen-eigen-b3f3d4950030\
configuration:
  - Release
  - Debug

install:
  - git submodule update --init --recursive
  # Get Eigen:
  - ps: wget http://bitbucket.org/eigen/eigen/get/3.3.5.zip -OutFile eigen.zip
  - cmd: 7z x eigen.zip -o"C:\projects" -y > nul

before_build:
    - cd %APPVEYOR_BUILD_FOLDER%
    - cmake -DBUILD_DOC=OFF -DBUILD_DEMO=ON -DBUILD_BENCH=OFF -DBUILD_TEST=OFF -DEIGEN3_INCLUDE_DIR=C:\projects\eigen-eigen-b3f3d4950030 -G "Visual Studio 15 2017 Win64" .
    - cd %APPVEYOR_BUILD_FOLDER%
    - dir
    - cd Examples
    - dir
build:
  project: $(APPVEYOR_BUILD_FOLDER)/Examples/gSparse-Examples.sln

